[build]
builder = "NIXPACKS"

[variables]
TAILSCALE_VERSION = "latest"
TAILSCALE_HOSTNAME = "railway-backend-medusa"
TAILSCALE_ADDITIONAL_ARGS = ""
TAILSCALE_AUTHKEY = ""
DATABASE_TYPE = "postgres"
#DATABASE_URL = "${{Postgres.DATABASE_URL}}"
#REDIS_URL = "{{Redis.REDIS_URL}}"
STORE_CORS = "https://leky.hr, https://byq-storefront-medusa.vercel.app, http://localhost:8000,http://localhost:7003"
MEDUSA_ADMIN_ONBOARDING_NEXTJS_DIRECTORY = "backend-medusa-storefront" # not needed?
MEDUSA_ADMIN_ONBOARDING_TYPE = "nextjs" # not needed?
ALGOLIA_ADMIN_API_KEY = "ef8241f606fe3838fc5bfc5a8ba6a97f" # Should be changed for different enviroments
ALGOLIA_APP_ID = "5DYEZ0TC15" # Should be changed for different enviroments

JWT_SECRET="jahsdjashjhkhk" # Remove from this file so it's not in github repo
COOKIE_SECRET="jahsdjashjhkhk" # Remove from this file so it's not in github repo


[phases.setup]
nixPkgs = ['nodejs', 'yarn']
aptPkgs = ["wget"]   # Install the wget package with apt-get

[phases.setupTailScale]
cmds = ["wget https://pkgs.tailscale.com/stable/tailscale_latest_amd64.tgz", "tar xzf tailscale_latest_amd64.tgz --strip-components=1", "mkdir -p /var/run/tailscale /var/cache/tailscale /var/lib/tailscale"]

[phases.install]
cacheDirectories = ['node_modules/.cache']
cmd=['yarn install']

[phases.build]
cacheDirectories = ['node_modules/.cache']
cmd=["yarn build"]

[start]
#cmd = "./start_sleep.sh"
cmd = "./start.sh"
